find_path(PALISADE_CORE_INCLUDE_DIR NAMES palisadecore.h PATH_SUFFIXES palisade/core)
find_library(PALISADE_CORE_LIBRARY NAMES libPALISADEcore.so)

find_path(PALISADE_CEREAL_INCLUDE_DIR NAMES cereal/cereal.hpp PATH_SUFFIXES palisade)

find_path(PALISADE_PKE_INCLUDE_DIR NAMES palisade.h PATH_SUFFIXES palisade/pke)
find_library(PALISADE_PKE_LIBRARY NAMES libPALISADEpke.so)

#set(LP_FOUND TRUE)
set(PALISADE_INCLUDE_DIR ${PALISADE_CORE_INCLUDE_DIR} ${PALISADE_PKE_INCLUDE_DIR} ${PALISADE_CEREAL_INCLUDE_DIR})
set(PALISADE_LIBRARY ${PALISADE_CORE_LIBRARY} ${PALISADE_PKE_LIBRARY})

set(PALISADE_INCLUDE_DIRS ${PALISADE_INCLUDE_DIR})
set(PALISADE_LIBRARIES ${PALISADE_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PALISADE DEFAULT_MSG
        PALISADE_LIBRARY PALISADE_INCLUDE_DIR)

mark_as_advanced(PALISADE_LIBRARY PALISADE_INCLUDE_DIR)

